"""Generated mapping from ISO 639 language code/tag to iNaturalist vernacular CSV file names.

Sources:
- CSV `language` column for files that already declare a real language code/tag.
- vernacular-und-language-code-attempt.json for files whose Darwin Core language column is `und`.
- Filename/lexicon overrides for more specific tags such as script or region variants.

Some codes map to multiple CSVs because the archive contains aliases, dialect labels,
regional lexicons, or duplicate lexicon names for the same ISO code.
"""

from __future__ import annotations

VERNACULAR_LANGUAGE_CODE_TO_CSV_FILES: dict[str, tuple[str, ...]] = {
    'aa': ('VernacularNames-afar.csv',),
    'ab': ('VernacularNames-abkhazian.csv',),
    'abe': ('VernacularNames-abenaki.csv',),
    'abg': ('VernacularNames-abaga.csv',),
    'ace': ('VernacularNames-acehnese.csv',),
    'acf': ('VernacularNames-kweyol.csv',),
    'ach': ('VernacularNames-acholi.csv',),
    'acv': ('VernacularNames-achumawi.csv',),
    'ada': ('VernacularNames-adangme.csv',),
    'adj': ('VernacularNames-adioukrou.csv',),
    'adt': ('VernacularNames-adnyamathanha.csv',),
    'ady': ('VernacularNames-adyghe.csv',),
    'af': ('VernacularNames-afrikaans.csv',),
    'agn': ('VernacularNames-agutaynen.csv',),
    'ain': ('VernacularNames-ainu.csv',),
    'ak': ('VernacularNames-akan.csv',),
    'ake': ('VernacularNames-akawaio.csv',),
    'akz': ('VernacularNames-alabama.csv',),
    'ale': ('VernacularNames-aleut.csv',),
    'als': ('VernacularNames-tosk-albanian.csv',),
    'alt': ('VernacularNames-southern-altai.csv',),
    'aly': ('VernacularNames-alyawarr.csv',),
    'alz': ('VernacularNames-alur.csv',),
    'am': ('VernacularNames-amharic.csv',),
    'ami': ('VernacularNames-amis.csv',),
    'an': ('VernacularNames-aragonese.csv',),
    'aqc': ('VernacularNames-archi.csv',),
    'ar': ('VernacularNames-arabic.csv',),
    'arl': ('VernacularNames-arabela.csv',),
    'arn': (
        'VernacularNames-mapuche.csv',
        'VernacularNames-mapudungun.csv',
    ),
    'arp': ('VernacularNames-arapaho.csv',),
    'as': ('VernacularNames-assamese.csv',),
    'ast': ('VernacularNames-asturian.csv',),
    'atj': ('VernacularNames-atikamekw.csv',),
    'av': (
        'VernacularNames-avar.csv',
        'VernacularNames-avaric.csv',
    ),
    'avk': ('VernacularNames-kotava.csv',),
    'ay': ('VernacularNames-aymara.csv',),
    'az': ('VernacularNames-azerbaijani.csv',),
    'azb': ('VernacularNames-south-azerbaijani.csv',),
    'ba': ('VernacularNames-bashkir.csv',),
    'ban': ('VernacularNames-balinese.csv',),
    'bar': ('VernacularNames-bavarian.csv',),
    'bck': ('VernacularNames-bunuba.csv',),
    'bcl': ('VernacularNames-central-bikol.csv',),
    'bdm': ('VernacularNames-buduma.csv',),
    'bdp': ('VernacularNames-bende.csv',),
    'be': ('VernacularNames-belarusian.csv',),
    'bem': ('VernacularNames-bemba.csv',),
    'bg': ('VernacularNames-bulgarian.csv',),
    'bho': ('VernacularNames-bhojpuri.csv',),
    'bi': ('VernacularNames-bislama.csv',),
    'bib': ('VernacularNames-bisa.csv',),
    'bik': ('VernacularNames-bikol.csv',),
    'bin': ('VernacularNames-bini.csv',),
    'bjn': ('VernacularNames-banjar.csv',),
    'bla': ('VernacularNames-siksika.csv',),
    'bll': ('VernacularNames-biloxi.csv',),
    'bm': ('VernacularNames-bambara.csv',),
    'bn': ('VernacularNames-bengali.csv',),
    'bnn': ('VernacularNames-bunun.csv',),
    'bno': ('VernacularNames-bantoanon.csv',),
    'bo': ('VernacularNames-tibetan.csv',),
    'bob': ('VernacularNames-boni.csv',),
    'bou': ('VernacularNames-bondei.csv',),
    'bpy': ('VernacularNames-bishnupriya.csv',),
    'br': ('VernacularNames-breton.csv',),
    'brl': ('VernacularNames-birwa.csv',),
    'brn': ('VernacularNames-boruca.csv',),
    'bs': ('VernacularNames-bosnian.csv',),
    'bsa': ('VernacularNames-abinomn.csv',),
    'bta': ('VernacularNames-bata.csv',),
    'btx': ('VernacularNames-batak-karo.csv',),
    'bvb': ('VernacularNames-bube.csv',),
    'bww': ('VernacularNames-bwa.csv',),
    'byn': ('VernacularNames-bilen.csv',),
    'bzd': ('VernacularNames-bribri.csv',),
    'ca': (
        'VernacularNames-catalan.csv',
        'VernacularNames-valencian.csv',
    ),
    'cak': ('VernacularNames-kaqchikel.csv',),
    'cal': ('VernacularNames-carolinian.csv',),
    'car': ('VernacularNames-carib.csv',),
    'cay': ('VernacularNames-cayuga.csv',),
    'cbk': ('VernacularNames-chavacano.csv',),
    'cce': ('VernacularNames-chopi.csv',),
    'cdo': ('VernacularNames-min-dong-chinese.csv',),
    'ce': ('VernacularNames-chechen.csv',),
    'ceb': ('VernacularNames-cebuano.csv',),
    'cgc': ('VernacularNames-kagayanen.csv',),
    'ch': ('VernacularNames-chamorro.csv',),
    'chc': ('VernacularNames-catawba.csv',),
    'chl': ('VernacularNames-cahuilla.csv',),
    'chn': ('VernacularNames-chinuk-wawa.csv',),
    'cho': ('VernacularNames-choctaw.csv',),
    'chr': ('VernacularNames-cherokee.csv',),
    'chs': ('VernacularNames-chumash.csv',),
    'chy': ('VernacularNames-cheyenne.csv',),
    'ciw': ('VernacularNames-chippewa.csv',),
    'cjk': ('VernacularNames-chokwe.csv',),
    'cjp': ('VernacularNames-cabecar.csv',),
    'ckb': ('VernacularNames-central-kurdish.csv',),
    'ckt': ('VernacularNames-chukot.csv',),
    'cku': ('VernacularNames-koasati.csv',),
    'clm': ('VernacularNames-klallam.csv',),
    'cmn': ('VernacularNames-mandarin-chinese.csv',),
    'co': (
        'VernacularNames-corsican.csv',
        'VernacularNames-corsu.csv',
    ),
    'coj': ('VernacularNames-cochimi.csv',),
    'con': ('VernacularNames-cofan.csv',),
    'cpe': ('VernacularNames-english-creole.csv',),
    'cr': ('VernacularNames-cree.csv',),
    'crg': ('VernacularNames-michif.csv',),
    'crh': (
        'VernacularNames-crimean-tatar.csv',
        'VernacularNames-crimean-turkish.csv',
    ),
    'cs': ('VernacularNames-czech.csv',),
    'csb': ('VernacularNames-kashubian.csv',),
    'ctu': ('VernacularNames-chol.csv',),
    'cu': (
        'VernacularNames-church-slavic.csv',
        'VernacularNames-old-church-slavonic.csv',
    ),
    'cv': ('VernacularNames-chuvash.csv',),
    'cy': ('VernacularNames-welsh.csv',),
    'da': ('VernacularNames-danish.csv',),
    'dag': ('VernacularNames-dagbani.csv',),
    'dak': ('VernacularNames-dakota.csv',),
    'dav': ('VernacularNames-taita.csv',),
    'daw': ('VernacularNames-davawenyo.csv',),
    'ddg': ('VernacularNames-fataluku.csv',),
    'de': ('VernacularNames-german.csv',),
    'dig': ('VernacularNames-digo.csv',),
    'din': ('VernacularNames-dinka.csv',),
    'dmm': ('VernacularNames-dama.csv',),
    'doi': ('VernacularNames-dogri.csv',),
    'dru': ('VernacularNames-rukai.csv',),
    'dsb': ('VernacularNames-lower-sorbian.csv',),
    'dsh': ('VernacularNames-daasanach.csv',),
    'dua': ('VernacularNames-duala.csv',),
    'dug': ('VernacularNames-duruma.csv',),
    'dv': (
        'VernacularNames-divehi.csv',
        'VernacularNames-maldivian.csv',
    ),
    'dyo': ('VernacularNames-jola-fonyi.csv',),
    'dyu': ('VernacularNames-jula.csv',),
    'dz': ('VernacularNames-dzongkha.csv',),
    'ebu': ('VernacularNames-embu.csv',),
    'ee': ('VernacularNames-ewe.csv',),
    'efi': ('VernacularNames-efik.csv',),
    'el': ('VernacularNames-greek.csv',),
    'elo': ('VernacularNames-el-molo.csv',),
    'en': (
        'VernacularNames-appalachian-english.csv',
        'VernacularNames-bonin-english.csv',
        'VernacularNames-english.csv',
        'VernacularNames-manx-english-dialect.csv',
    ),
    'en-IN': ('VernacularNames-english-indian.csv',),
    'en-SG': ('VernacularNames-singlish.csv',),
    'eo': ('VernacularNames-esperanto.csv',),
    'es': ('VernacularNames-spanish.csv',),
    'es-419': ('VernacularNames-espanol-latinoamerica.csv',),
    'et': ('VernacularNames-estonian.csv',),
    'eu': (
        'VernacularNames-basque.csv',
        'VernacularNames-euskara.csv',
    ),
    'ext': ('VernacularNames-extremaduran.csv',),
    'fa': (
        'VernacularNames-farsi.csv',
        'VernacularNames-persian.csv',
    ),
    'fan': ('VernacularNames-fang.csv',),
    'ff': (
        'VernacularNames-fula.csv',
        'VernacularNames-fulfulde.csv',
    ),
    'fi': ('VernacularNames-finnish.csv',),
    'fil': ('VernacularNames-filipino.csv',),
    'fj': ('VernacularNames-fijian.csv',),
    'fo': ('VernacularNames-faroese.csv',),
    'fon': ('VernacularNames-fon-gbe.csv',),
    'fr': ('VernacularNames-french.csv',),
    'fr-CA': ('VernacularNames-francais-du-canada.csv',),
    'frc': ('VernacularNames-cajun-french.csv',),
    'frr': ('VernacularNames-northern-frisian.csv',),
    'fur': ('VernacularNames-friulian.csv',),
    'fwa': ('VernacularNames-fwai.csv',),
    'fwe': ('VernacularNames-fwe.csv',),
    'fy': ('VernacularNames-west-frisian.csv',),
    'ga': ('VernacularNames-irish.csv',),
    'gaa': ('VernacularNames-ga.csv',),
    'gag': ('VernacularNames-gagauz.csv',),
    'gan': ('VernacularNames-gan-chinese.csv',),
    'gbb': ('VernacularNames-kaytetye.csv',),
    'gbr': ('VernacularNames-gbagyi.csv',),
    'gd': ('VernacularNames-scottish-gaelic.csv',),
    'gl': (
        'VernacularNames-galego.csv',
        'VernacularNames-galician.csv',
    ),
    'glk': ('VernacularNames-gilaki.csv',),
    'gn': ('VernacularNames-guarani.csv',),
    'gog': ('VernacularNames-gogo.csv',),
    'gom': ('VernacularNames-goan-konkani.csv',),
    'gor': ('VernacularNames-gorontalo.csv',),
    'got': ('VernacularNames-gothic.csv',),
    'gow': ('VernacularNames-gorowa.csv',),
    'gsw': (
        'VernacularNames-alemannic.csv',
        'VernacularNames-swiss-german.csv',
    ),
    'gu': (
        'VernacularNames-gujarati-kathiawadi.csv',
        'VernacularNames-gujarati.csv',
    ),
    'guc': ('VernacularNames-wayuu.csv',),
    'guz': ('VernacularNames-gusii.csv',),
    'gv': ('VernacularNames-manx.csv',),
    'gwi': ('VernacularNames-gwich-in.csv',),
    'ha': ('VernacularNames-hausa.csv',),
    'hai': ('VernacularNames-haida.csv',),
    'hak': ('VernacularNames-hakka-chinese.csv',),
    'haw': ('VernacularNames-hawaiian.csv',),
    'hay': ('VernacularNames-haya.csv',),
    'hch': ('VernacularNames-huichol.csv',),
    'he': ('VernacularNames-hebrew.csv',),
    'heh': ('VernacularNames-hehe.csv',),
    'hei': ('VernacularNames-heiltsuk.csv',),
    'hi': ('VernacularNames-hindi.csv',),
    'hid': ('VernacularNames-hidatsa.csv',),
    'hif': ('VernacularNames-fiji-hindi.csv',),
    'hil': ('VernacularNames-hiligaynon.csv',),
    'ho': ('VernacularNames-hiri-motu.csv',),
    'hop': ('VernacularNames-hopi.csv',),
    'hr': ('VernacularNames-croatian.csv',),
    'hsb': ('VernacularNames-upper-sorbian.csv',),
    'ht': (
        'VernacularNames-haitian-creole.csv',
        'VernacularNames-haitian.csv',
    ),
    'hu': ('VernacularNames-hungarian.csv',),
    'hy': ('VernacularNames-armenian.csv',),
    'hyw': ('VernacularNames-western-armenian.csv',),
    'hz': ('VernacularNames-herero.csv',),
    'ia': ('VernacularNames-interlingua.csv',),
    'iba': ('VernacularNames-iban.csv',),
    'ibd': ('VernacularNames-iwaidja.csv',),
    'id': ('VernacularNames-indonesian.csv',),
    'ig': ('VernacularNames-igbo.csv',),
    'ijc': ('VernacularNames-izon.csv',),
    'ijo': ('VernacularNames-ijo.csv',),
    'ik': ('VernacularNames-inupiaq.csv',),
    'ilb': ('VernacularNames-ila.csv',),
    'ilo': (
        'VernacularNames-ilokano.csv',
        'VernacularNames-iloko.csv',
    ),
    'inh': ('VernacularNames-ingush.csv',),
    'io': ('VernacularNames-ido.csv',),
    'irk': ('VernacularNames-iraqw.csv',),
    'is': ('VernacularNames-icelandic.csv',),
    'isv': ('VernacularNames-interslavic.csv',),
    'it': ('VernacularNames-italian.csv',),
    'iu': ('VernacularNames-inuktitut.csv',),
    'ivv': ('VernacularNames-ivatan.csv',),
    'ja': ('VernacularNames-japanese.csv',),
    'jaz': ('VernacularNames-jawe.csv',),
    'jbo': ('VernacularNames-lojban.csv',),
    'jbu': ('VernacularNames-jukun-takum.csv',),
    'jei': ('VernacularNames-yei.csv',),
    'jiv': ('VernacularNames-shuar.csv',),
    'jv': ('VernacularNames-javanese.csv',),
    'ka': ('VernacularNames-georgian.csv',),
    'kaa': ('VernacularNames-kara-kalpak.csv',),
    'kab': ('VernacularNames-kabyle.csv',),
    'kam': ('VernacularNames-kamba.csv',),
    'kao': ('VernacularNames-xaasongaxango.csv',),
    'kbd': ('VernacularNames-kabardian.csv',),
    'kbl': ('VernacularNames-kanembu.csv',),
    'kbp': ('VernacularNames-kabiye.csv',),
    'kca': ('VernacularNames-khanty.csv',),
    'kck': ('VernacularNames-kalanga.csv',),
    'kcn': ('VernacularNames-nubi.csv',),
    'kde': ('VernacularNames-makonde.csv',),
    'kdk': ('VernacularNames-numee.csv',),
    'kdn': ('VernacularNames-kunda.csv',),
    'kdq': ('VernacularNames-koch.csv',),
    'keb': ('VernacularNames-kele.csv',),
    'kek': ('VernacularNames-maya-q-eqchi.csv',),
    'kfl': ('VernacularNames-kung.csv',),
    'kfr': ('VernacularNames-kutchi.csv',),
    'kg': ('VernacularNames-kongo.csv',),
    'kha': ('VernacularNames-khasi.csv',),
    'ki': ('VernacularNames-kikuyu.csv',),
    'kia': ('VernacularNames-kim.csv',),
    'kio': ('VernacularNames-kiowa.csv',),
    'kj': (
        'VernacularNames-kwanyama-ovamboland.csv',
        'VernacularNames-kwanyama.csv',
        'VernacularNames-oshikwanyama.csv',
    ),
    'kjh': ('VernacularNames-khakas.csv',),
    'kk': ('VernacularNames-kazakh.csv',),
    'kl': (
        'VernacularNames-greenlandic.csv',
        'VernacularNames-kalaallisut.csv',
    ),
    'km': ('VernacularNames-khmer.csv',),
    'kmb': ('VernacularNames-kimbundu.csv',),
    'kn': ('VernacularNames-kannada.csv',),
    'ko': ('VernacularNames-korean.csv',),
    'koi': ('VernacularNames-komi-permyak.csv',),
    'kok': ('VernacularNames-konkani.csv',),
    'kos': ('VernacularNames-kosraean.csv',),
    'kpd': ('VernacularNames-koba.csv',),
    'kqn': ('VernacularNames-kaonde.csv',),
    'kqu': ('VernacularNames-seroa.csv',),
    'kqz': ('VernacularNames-korana.csv',),
    'kr': ('VernacularNames-kanuri.csv',),
    'kri': ('VernacularNames-krio.csv',),
    'krl': ('VernacularNames-karelian.csv',),
    'ks': ('VernacularNames-kashmiri.csv',),
    'ksb': ('VernacularNames-shambala.csv',),
    'ksh': ('VernacularNames-colognian.csv',),
    'kth': ('VernacularNames-karanga.csv',),
    'ktz': (
        'VernacularNames-ju-hoan.csv',
        'VernacularNames-juhoansi.csv',
    ),
    'ku': ('VernacularNames-kurdish.csv',),
    'kuj': ('VernacularNames-kuria.csv',),
    'kun': ('VernacularNames-kunama.csv',),
    'kut': ('VernacularNames-ktunaxa.csv',),
    'kuz': ('VernacularNames-kunza.csv',),
    'kv': ('VernacularNames-komi.csv',),
    'kw': ('VernacularNames-cornish.csv',),
    'kwk': ('VernacularNames-kwak-wala.csv',),
    'kwm': ('VernacularNames-kwambi.csv',),
    'kwn': ('VernacularNames-kwangali.csv',),
    'ky': (
        'VernacularNames-kirghiz.csv',
        'VernacularNames-kyrgyz.csv',
    ),
    'la': ('VernacularNames-latin.csv',),
    'lac': (
        'VernacularNames-lacandon-maya.csv',
        'VernacularNames-lacandon.csv',
        'VernacularNames-maya-lacandon.csv',
    ),
    'lad': ('VernacularNames-ladino.csv',),
    'lag': ('VernacularNames-rangi.csv',),
    'lah': ('VernacularNames-western-punjabi.csv',),
    'lam': ('VernacularNames-lamba.csv',),
    'lb': ('VernacularNames-luxembourgish.csv',),
    'lbe': ('VernacularNames-lak.csv',),
    'lbj': ('VernacularNames-ladakhi.csv',),
    'lbq': ('VernacularNames-wampar.csv',),
    'lch': ('VernacularNames-luchazi.csv',),
    'ldn': ('VernacularNames-laadan.csv',),
    'leh': ('VernacularNames-lenje.csv',),
    'lez': ('VernacularNames-lezghian.csv',),
    'lfn': ('VernacularNames-lingua-franca-nova.csv',),
    'lg': (
        'VernacularNames-ganda.csv',
        'VernacularNames-luganda.csv',
    ),
    'lgg': ('VernacularNames-lugbara.csv',),
    'li': ('VernacularNames-limburgish.csv',),
    'lij': ('VernacularNames-ligurian.csv',),
    'lkt': ('VernacularNames-lakota.csv',),
    'lld': ('VernacularNames-ladin.csv',),
    'lmo': ('VernacularNames-lombard.csv',),
    'ln': ('VernacularNames-lingala.csv',),
    'lo': ('VernacularNames-lao.csv',),
    'loo': ('VernacularNames-lombo.csv',),
    'loz': (
        'VernacularNames-lozi.csv',
        'VernacularNames-silozi.csv',
    ),
    'lt': ('VernacularNames-lithuanian.csv',),
    'ltg': ('VernacularNames-latgalian.csv',),
    'lua': ('VernacularNames-luba-kasai.csv',),
    'luc': ('VernacularNames-aringa.csv',),
    'lue': ('VernacularNames-luvale.csv',),
    'lun': ('VernacularNames-lunda.csv',),
    'luo': ('VernacularNames-dholuo.csv',),
    'lus': ('VernacularNames-mizo.csv',),
    'lv': ('VernacularNames-latvian.csv',),
    'lva': ('VernacularNames-makua.csv',),
    'lzh': ('VernacularNames-literary-chinese.csv',),
    'mad': ('VernacularNames-madurese.csv',),
    'mai': ('VernacularNames-maithili.csv',),
    'mak': ('VernacularNames-makassarese.csv',),
    'mas': ('VernacularNames-maasai.csv',),
    'maw': ('VernacularNames-mampruli.csv',),
    'mbc': ('VernacularNames-macushi.csv',),
    'mck': ('VernacularNames-mbunda.csv',),
    'mcs': ('VernacularNames-mambai.csv',),
    'mdf': ('VernacularNames-moksha.csv',),
    'men': ('VernacularNames-mende.csv',),
    'mer': ('VernacularNames-meru.csv',),
    'mfy': ('VernacularNames-mayo.csv',),
    'mg': ('VernacularNames-malagasy.csv',),
    'mgv': ('VernacularNames-matengo.csv',),
    'mgz': ('VernacularNames-mbugwe.csv',),
    'mh': ('VernacularNames-marshallese.csv',),
    'mhr': ('VernacularNames-eastern-mari.csv',),
    'mhw': ('VernacularNames-mbukushu.csv',),
    'mi': ('VernacularNames-maori.csv',),
    'mia': ('VernacularNames-miami.csv',),
    'mic': ('VernacularNames-mi-kmaq.csv',),
    'mik': ('VernacularNames-mikasuki.csv',),
    'miq': ('VernacularNames-miskito.csv',),
    'mk': ('VernacularNames-macedonian.csv',),
    'mkz': ('VernacularNames-makasae.csv',),
    'ml': ('VernacularNames-malayalam.csv',),
    'mlc': ('VernacularNames-cao-lan.csv',),
    'mlk': ('VernacularNames-ilwana.csv',),
    'mn': ('VernacularNames-mongolian.csv',),
    'mni': ('VernacularNames-manipuri.csv',),
    'mnk': ('VernacularNames-mandinka.csv',),
    'mnw': ('VernacularNames-mon.csv',),
    'moh': ('VernacularNames-mohawk.csv',),
    'mos': ('VernacularNames-moore.csv',),
    'mr': ('VernacularNames-marathi.csv',),
    'mrv': ('VernacularNames-mangareva.csv',),
    'mrw': ('VernacularNames-maranao.csv',),
    'ms': ('VernacularNames-malay.csv',),
    'mt': ('VernacularNames-maltese.csv',),
    'mus': (
        'VernacularNames-creek.csv',
        'VernacularNames-mvskoke.csv',
    ),
    'mwl': ('VernacularNames-mirandese.csv',),
    'mxc': ('VernacularNames-manyika.csv',),
    'my': ('VernacularNames-burmese.csv',),
    'myh': ('VernacularNames-makah.csv',),
    'myn': ('VernacularNames-maya.csv',),
    'myv': ('VernacularNames-erzya.csv',),
    'mzn': ('VernacularNames-mazanderani.csv',),
    'na': ('VernacularNames-nauruan.csv',),
    'nan': ('VernacularNames-chinese-min-nan.csv',),
    'nap': ('VernacularNames-neapolitan.csv',),
    'naq': ('VernacularNames-khoekhoegowab.csv',),
    'nb': ('VernacularNames-norwegian.csv',),
    'ndc': ('VernacularNames-ndau.csv',),
    'nds': (
        'VernacularNames-low-german.csv',
        'VernacularNames-low-saxon.csv',
    ),
    'ne': ('VernacularNames-nepali.csv',),
    'nem': ('VernacularNames-nemi.csv',),
    'nen': ('VernacularNames-nengone.csv',),
    'new': ('VernacularNames-newari.csv',),
    'nez': ('VernacularNames-nez-perce.csv',),
    'ng': ('VernacularNames-ndonga.csv',),
    'ngo': ('VernacularNames-ngoni.csv',),
    'nhr': ('VernacularNames-naro.csv',),
    'niq': ('VernacularNames-nandi.csv',),
    'niu': ('VernacularNames-niuean.csv',),
    'nka': ('VernacularNames-nkoya.csv',),
    'nl': ('VernacularNames-dutch.csv',),
    'nlg': ('VernacularNames-gela.csv',),
    'nmq': ('VernacularNames-nambya.csv',),
    'nn': ('VernacularNames-nynorsk.csv',),
    'nod': ('VernacularNames-northern-thai.csv',),
    'nov': ('VernacularNames-novial.csv',),
    'nqo': ('VernacularNames-n-ko.csv',),
    'nr': ('VernacularNames-ndebele.csv',),
    'nrb': ('VernacularNames-nara.csv',),
    'nrl': ('VernacularNames-ngarluma.csv',),
    'nse': ('VernacularNames-nsenga.csv',),
    'nso': (
        'VernacularNames-pedi.csv',
        'VernacularNames-sepedi.csv',
    ),
    'nsz': ('VernacularNames-nisenan.csv',),
    'nuk': ('VernacularNames-nuuchahnulth.csv',),
    'nus': ('VernacularNames-nuer.csv',),
    'nv': (
        'VernacularNames-navaho.csv',
        'VernacularNames-navajo.csv',
    ),
    'ny': (
        'VernacularNames-chewa.csv',
        'VernacularNames-nyanja.csv',
    ),
    'nyh': ('VernacularNames-nyikina.csv',),
    'nym': ('VernacularNames-nyamwezi.csv',),
    'nyo': ('VernacularNames-nyoro.csv',),
    'nys': ('VernacularNames-noongar.csv',),
    'nyu': ('VernacularNames-nyungwe.csv',),
    'nzi': ('VernacularNames-nzema.csv',),
    'oc': ('VernacularNames-occitan.csv',),
    'oj': ('VernacularNames-ojibwe.csv',),
    'om': ('VernacularNames-oromo.csv',),
    'oma': ('VernacularNames-omaha-ponca.csv',),
    'omi': ('VernacularNames-omi.csv',),
    'ono': ('VernacularNames-onondaga.csv',),
    'ood': ('VernacularNames-o-odham.csv',),
    'opt': ('VernacularNames-opata.csv',),
    'or': ('VernacularNames-oriya.csv',),
    'orc': ('VernacularNames-orma.csv',),
    'os': (
        'VernacularNames-ossetian.csv',
        'VernacularNames-ossetic.csv',
    ),
    'osd': ('VernacularNames-digor-ossetian.csv',),
    'pa': ('VernacularNames-punjabi.csv',),
    'pag': ('VernacularNames-pangasinan.csv',),
    'pam': (
        'VernacularNames-kapampangan.csv',
        'VernacularNames-pampanga.csv',
    ),
    'pap': (
        'VernacularNames-papiamento.csv',
        'VernacularNames-papiamentu.csv',
    ),
    'pau': ('VernacularNames-palauan.csv',),
    'pbc': ('VernacularNames-patamona.csv',),
    'pcd': ('VernacularNames-picard.csv',),
    'pdc': ('VernacularNames-pennsylvania-german.csv',),
    'pih': ('VernacularNames-norfuk.csv',),
    'pis': ('VernacularNames-pijin.csv',),
    'piz': ('VernacularNames-pije.csv',),
    'pkb': ('VernacularNames-pokomo.csv',),
    'pl': ('VernacularNames-polish.csv',),
    'pmm': ('VernacularNames-pomo.csv',),
    'pmt': ('VernacularNames-tuamotuan.csv',),
    'pny': ('VernacularNames-pinyin.csv',),
    'pon': ('VernacularNames-pohnpeian.csv',),
    'ppi': ('VernacularNames-paipai.csv',),
    'ppt': ('VernacularNames-pare.csv',),
    'ps': ('VernacularNames-pashto.csv',),
    'pt': ('VernacularNames-portuguese.csv',),
    'pt-BR': ('VernacularNames-portuguese-brasil.csv',),
    'pwn': ('VernacularNames-paiwan.csv',),
    'qu': (
        'VernacularNames-quechua.csv',
        'VernacularNames-runa-simi.csv',
    ),
    'rap': ('VernacularNames-rapanui.csv',),
    'ray': ('VernacularNames-rapa.csv',),
    'rel': ('VernacularNames-rendille.csv',),
    'rim': ('VernacularNames-nyaturu.csv',),
    'rm': (
        'VernacularNames-romansh.csv',
        'VernacularNames-rumantsch-vallader.csv',
    ),
    'rn': ('VernacularNames-rundi.csv',),
    'rng': ('VernacularNames-ronga.csv',),
    'ro': ('VernacularNames-romanian.csv',),
    'rol': ('VernacularNames-romblomanon.csv',),
    'rom': (
        'VernacularNames-romani.csv',
        'VernacularNames-romany.csv',
    ),
    'rrm': ('VernacularNames-moriori.csv',),
    'ru': ('VernacularNames-russian.csv',),
    'rub': ('VernacularNames-gungu.csv',),
    'rue': ('VernacularNames-rusyn.csv',),
    'ruf': ('VernacularNames-luguru.csv',),
    'rug': ('VernacularNames-roviana.csv',),
    'rup': ('VernacularNames-aromanian.csv',),
    'rw': ('VernacularNames-kinyarwanda.csv',),
    'sa': ('VernacularNames-sanskrit.csv',),
    'saq': ('VernacularNames-samburu.csv',),
    'sas': ('VernacularNames-sasak.csv',),
    'sat': ('VernacularNames-santali.csv',),
    'sbs': ('VernacularNames-subiya.csv',),
    'sc': ('VernacularNames-sardinian.csv',),
    'scn': ('VernacularNames-sicilian.csv',),
    'sco': ('VernacularNames-scots.csv',),
    'sd': ('VernacularNames-sindhi.csv',),
    'se': ('VernacularNames-northern-sami.csv',),
    'see': ('VernacularNames-seneca.csv',),
    'seh': ('VernacularNames-sena.csv',),
    'sei': ('VernacularNames-seri.csv',),
    'sey': ('VernacularNames-secoya.csv',),
    'sg': ('VernacularNames-sango.csv',),
    'sgc': ('VernacularNames-kipsigis.csv',),
    'sgs': ('VernacularNames-samogitian.csv',),
    'sh': ('VernacularNames-serbo-croatian.csv',),
    'shk': ('VernacularNames-shilluk.csv',),
    'shn': ('VernacularNames-shan.csv',),
    'si': (
        'VernacularNames-sinhala.csv',
        'VernacularNames-sinhalese.csv',
    ),
    'sk': (
        'VernacularNames-slovak.csv',
        'VernacularNames-slovencina.csv',
    ),
    'sl': ('VernacularNames-slovenian.csv',),
    'sm': ('VernacularNames-samoan.csv',),
    'smd': ('VernacularNames-sama.csv',),
    'smk': ('VernacularNames-bolinao.csv',),
    'smn': ('VernacularNames-inari-sami.csv',),
    'sms': ('VernacularNames-skolt-sami.csv',),
    'sn': ('VernacularNames-shona.csv',),
    'snk': ('VernacularNames-soninke.csv',),
    'snn': ('VernacularNames-siona.csv',),
    'so': ('VernacularNames-somali.csv',),
    'sq': ('VernacularNames-albanian.csv',),
    'squ': ('VernacularNames-squamish.csv',),
    'sr': ('VernacularNames-serbian.csv',),
    'srm': ('VernacularNames-saramaccan.csv',),
    'srn': ('VernacularNames-sranan-tongo.csv',),
    'srr': ('VernacularNames-serer.csv',),
    'srs': ('VernacularNames-tsuut-ina.csv',),
    'ss': (
        'VernacularNames-swati.csv',
        'VernacularNames-swazi.csv',
    ),
    'ssy': ('VernacularNames-saho.csv',),
    'su': ('VernacularNames-sundanese.csv',),
    'sub': ('VernacularNames-suku.csv',),
    'suk': ('VernacularNames-sukuma.csv',),
    'sus': ('VernacularNames-susu.csv',),
    'sv': ('VernacularNames-swedish.csv',),
    'sw': ('VernacularNames-swahili.csv',),
    'szl': ('VernacularNames-silesian.csv',),
    'szy': ('VernacularNames-sakizaya.csv',),
    'ta': ('VernacularNames-tamil.csv',),
    'tap': ('VernacularNames-taabwa.csv',),
    'tay': ('VernacularNames-atayal-taiwan.csv',),
    'tbh': ('VernacularNames-dharawal.csv',),
    'tcy': ('VernacularNames-tulu.csv',),
    'te': ('VernacularNames-telugu.csv',),
    'tem': ('VernacularNames-temne.csv',),
    'teo': ('VernacularNames-teso.csv',),
    'tet': ('VernacularNames-tetum.csv',),
    'tfn': ('VernacularNames-tanaina.csv',),
    'tg': ('VernacularNames-tajik.csv',),
    'th': ('VernacularNames-thai.csv',),
    'ti': ('VernacularNames-tigrinya.csv',),
    'tig': ('VernacularNames-tigre.csv',),
    'tiv': ('VernacularNames-tiv.csv',),
    'tiw': ('VernacularNames-tiwi.csv',),
    'tjm': ('VernacularNames-timucua.csv',),
    'tk': ('VernacularNames-turkmen.csv',),
    'tkl': ('VernacularNames-tokelauan.csv',),
    'tl': ('VernacularNames-tagalog.csv',),
    'tly': ('VernacularNames-talysh.csv',),
    'tn': ('VernacularNames-tswana.csv',),
    'tnq': ('VernacularNames-taino.csv',),
    'tny': ('VernacularNames-tongwe.csv',),
    'to': ('VernacularNames-tongan.csv',),
    'toj': ('VernacularNames-tojolabal.csv',),
    'tok': ('VernacularNames-toki-pona.csv',),
    'tox': ('VernacularNames-tobian.csv',),
    'tpi': ('VernacularNames-tok-pisin.csv',),
    'tpw': ('VernacularNames-tupi.csv',),
    'tr': ('VernacularNames-turkish.csv',),
    'ts': (
        'VernacularNames-tsonga.csv',
        'VernacularNames-xitsonga.csv',
    ),
    'tsi': ('VernacularNames-tsimshian.csv',),
    'tsz': ('VernacularNames-purepecha.csv',),
    'tt': ('VernacularNames-tatar.csv',),
    'tum': ('VernacularNames-tumbuka.csv',),
    'tun': ('VernacularNames-tunica.csv',),
    'tus': ('VernacularNames-tuscarora.csv',),
    'tuv': ('VernacularNames-turkana.csv',),
    'tuy': ('VernacularNames-tugen.csv',),
    'tvl': ('VernacularNames-tuvaluan.csv',),
    'tvs': ('VernacularNames-taveta.csv',),
    'tw': ('VernacularNames-twi.csv',),
    'ty': ('VernacularNames-tahitian.csv',),
    'tyv': (
        'VernacularNames-tuvan.csv',
        'VernacularNames-tuvinian.csv',
    ),
    'tzh': ('VernacularNames-tzeltal.csv',),
    'tzo': ('VernacularNames-tzotzil.csv',),
    'udm': ('VernacularNames-udmurt.csv',),
    'ug': ('VernacularNames-uyghur.csv',),
    'uk': ('VernacularNames-ukrainian.csv',),
    'umb': ('VernacularNames-umbundu.csv',),
    'unm': ('VernacularNames-unami.csv',),
    'ur': ('VernacularNames-urdu.csv',),
    'urk': ('VernacularNames-urak-lawoi.csv',),
    'uz': ('VernacularNames-uzbek.csv',),
    'vaj': ('VernacularNames-vasekele.csv',),
    've': (
        'VernacularNames-tshivenda.csv',
        'VernacularNames-venda.csv',
    ),
    'vec': (
        'VernacularNames-venetian.csv',
        'VernacularNames-veneto.csv',
    ),
    'vep': ('VernacularNames-veps.csv',),
    'vi': ('VernacularNames-vietnamese.csv',),
    'vif': ('VernacularNames-vili.csv',),
    'vmw': ('VernacularNames-makhuwa.csv',),
    'vo': ('VernacularNames-volapuk.csv',),
    'wa': ('VernacularNames-walloon.csv',),
    'wam': ('VernacularNames-wampanoag.csv',),
    'wap': ('VernacularNames-wapishana.csv',),
    'was': ('VernacularNames-washo.csv',),
    'way': ('VernacularNames-wayana.csv',),
    'wbp': ('VernacularNames-warlpiri.csv',),
    'wca': ('VernacularNames-yanomami.csv',),
    'wes': ('VernacularNames-cameroon-pidgin.csv',),
    'win': ('VernacularNames-ho-chunk.csv',),
    'wlk': ('VernacularNames-wailaki.csv',),
    'wls': ('VernacularNames-wallisian.csv',),
    'wmt': ('VernacularNames-walmajarri.csv',),
    'wo': ('VernacularNames-wolof.csv',),
    'wuu': ('VernacularNames-wuu-chinese.csv',),
    'xad': ('VernacularNames-adai.csv',),
    'xal': ('VernacularNames-kalmyk.csv',),
    'xam': ('VernacularNames-xam.csv',),
    'xh': ('VernacularNames-xhosa.csv',),
    'xmf': ('VernacularNames-mingrelian.csv',),
    'xuu': ('VernacularNames-kxoe.csv',),
    'xwa': ('VernacularNames-kwaza.csv',),
    'yao': ('VernacularNames-yao.csv',),
    'yaq': ('VernacularNames-yaqui.csv',),
    'ycr': ('VernacularNames-yilan-creole.csv',),
    'yi': ('VernacularNames-yiddish.csv',),
    'ynn': ('VernacularNames-yana.csv',),
    'yo': ('VernacularNames-yoruba.csv',),
    'yua': ('VernacularNames-maya-peninsular.csv',),
    'yur': ('VernacularNames-yurok.csv',),
    'za': ('VernacularNames-zhuang.csv',),
    'zaj': ('VernacularNames-zaramo.csv',),
    'zh': ('VernacularNames-chinese.csv',),
    'zh-CN': ('VernacularNames-chinese-simplified.csv',),
    'zh-Hant': ('VernacularNames-chinese-traditional.csv',),
    'zin': ('VernacularNames-zinza.csv',),
    'ziw': ('VernacularNames-zigula.csv',),
    'zu': ('VernacularNames-zulu.csv',),
    'zza': (
        'VernacularNames-zaza.csv',
        'VernacularNames-zazaki.csv',
    ),
}
